### ISSUE TITLE
Create Craft CMS structures that maps beta.gigadb.org/site/  structure

### ISSUE THREAD

**Issue by rija** [gigascience/cms#1]
## User story

As a curator
I want to be able to change the content under gigadb.org/site on my own
So that gigadb.org/site can be kept up-to-date  quickly without using development resource

## Acceptance criteria

Given I want to manage content from gigadb.org/site
When I login to CraftCMS as a content editor
Then I can see all the content that's existing at gigadb.org/site

Given I want to manage content from gigadb.org/site
When I login to CraftCMS as a content editor
Then I can manage, update or delete the content that's available at gigadb.org/site

## Additional Info

* [ ] Content audit
* [ ] Define content architecture based on gigadb.org/site/
* [ ] Start local setup and create and document content models and forms element in the CMS

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)
