### ISSUE TITLE
Create content layers field

### ISSUE THREAD

**Issue by adrienne** [gigascience/cms#11]
# Task for user story: #1 

## Describe the task to do

* [ ] Install [Tablemaker](https://plugins.craftcms.com/tablemaker?craft4) plugin
* [ ] Evaluate and install [Neo](https://plugins.craftcms.com/neo?craft4) or [Vizy](https://plugins.craftcms.com/vizy?craft4)
* [ ] Set up media layer types (gallery and video)
* [ ] Set up table layer type
* [ ] Set up text layer type
* [ ] Set up raw HTML layer type
* [ ] Set up actual field

## Ready Checklist

* [ ] The functionality is working locally
* [ ] There is appropriate documentation
* [ ] There is appropriate testing
* [ ] Data security has not been compromised
* [ ] No deviation from the team technology stack and software architecture has been introduced
