### ISSUE TITLE
Create global content

### ISSUE THREAD

**Issue by adrienne** [gigascience/cms#2]
# Task for user story: #1 

## Create all fields and global container for content

* [x] Install and configure [Navigation](https://plugins.craftcms.com/navigation?craft4) plugin
* [ ] Add Asset volume (need to connect with @rija for info)
* [x] Create Single for all global content
* [x] Create Matrix for social links
* [x] Create asset fields for primary & secondary logos
* [x] Create header & footer items

## Ready Checklist

* [x] The functionality is working locally
* [ ] There is appropriate documentation
* [x] There is appropriate testing
* [x] Data security has not been compromised
* [x] No deviation from the team technology stack and software architecture has been introduced
