### ISSUE TITLE
Create Pages channel

### ISSUE THREAD

**Issue by adrienne** [gigascience/cms#3]
# Task for user story: #1 

## Create Pages channel

* [ ] Set up page fields
* [ ] Set up Pages section (Structure-type section)
* [ ] Set up page types: regular, subpage, Team, Jobs, FAQ, Guidelines
* [ ] Create empty page tree

## Ready Checklist

* [ ] The functionality is working locally
* [ ] There is appropriate documentation
* [ ] There is appropriate testing
* [ ] Data security has not been compromised
* [ ] No deviation from the team technology stack and software architecture has been introduced

**Comment by adrienne** [comment]
Note: moved some subtasks to #11
