### ISSUE TITLE
Create Team Members channel

### ISSUE THREAD

**Issue by adrienne** [gigascience/cms#4]
# Task for user story: #1 

## Create Team Members channel

* [x] Set up fields
* [x] Create section
* [ ] Populate with some basic content

## Ready Checklist

* [x] The functionality is working locally
* [ ] There is appropriate documentation
* [x] There is appropriate testing
* [x] Data security has not been compromised
* [x] No deviation from the team technology stack and software architecture has been introduced
