### ISSUE TITLE
Create Checklists channel

### ISSUE THREAD

**Issue by adrienne** [gigascience/cms#6]
# Task for user story: #1 

## Create Checklists channel

* [ ] Set up fields
* [ ] Create section
* [ ] Populate with some basic content

## Ready Checklist

* [ ] The functionality is working locally
* [ ] There is appropriate documentation
* [ ] There is appropriate testing
* [ ] Data security has not been compromised
* [ ] No deviation from the team technology stack and software architecture has been introduced
