### ISSUE TITLE
Create Jobs channel

### ISSUE THREAD

**Issue by adrienne** [gigascience/cms#7]
# Task for user story: #1 

## Create Jobs channel

* [ ] Set up fields
* [ ] Create section
* [ ] Populate with some basic content
* [ ] Set up global content for Jobs in the Globals single

## Ready Checklist

* [ ] The functionality is working locally
* [ ] There is appropriate documentation
* [ ] There is appropriate testing
* [ ] Data security has not been compromised
* [ ] No deviation from the team technology stack and software architecture has been introduced
